language: java
jdk:
  - oraclejdk8

dist: trusty

sudo: false

before_install:
  - /bin/sh ./before_install.sh
  
install: 
  - mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V


script:
  - mvn test -P !build-extras -B -e 

cache:
  directories:
    - ~/.m2/repository

after_success:
  - /bin/sh ./before_deploy.sh
  - /bin/sh ./deploy.sh
  
after_failure:
  - cat target/surefire-reports/*.txt  

#deploy:
#  skip_cleanup: true
#  provider: script
#  script:
#    - /bin/sh ./before_deploy.sh
#    - /bin/sh ./deploy.sh
#  on:
#    tags: true
